// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUNewsManagementSystem.Repo.Models;

public partial class SystemAccount
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string AccountEmail { get; set; }

    public int AccountRole { get; set; }

    public string AccountPassword { get; set; }

    public virtual ICollection<NewsArticle> NewsArticleCreatedBy { get; set; } = new List<NewsArticle>();

    public virtual ICollection<NewsArticle> NewsArticleUpdatedBy { get; set; } = new List<NewsArticle>();
}